[package]
name = "chap-3"
version = "0.1.0"
authors = ["David Campion <David.Campion@walmartlabs.com>"]
edition = "2018"

[toolchain]
channel = "nightly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
